
import { NgModule } from '@angular/core';

import {
  MatSlideToggleModule,
  MatTableModule,
  MatToolbarModule,
  MatDialogModule,
  MatRadioModule,
  MatButtonModule,
  MatExpansionModule,
  MatStepperModule,
  MatDatepickerModule,
  MatTooltipModule,
  MatNativeDateModule,
  MatSelectModule,
  MatSnackBarModule,
  MatProgressSpinnerModule,
  MatListModule,
  MatGridListModule,
  MatCardModule,
  MatSidenavModule,
  MatInputModule,
  MatTabsModule,
  MatCheckboxModule,
  MatMenuModule,
  MatIconModule,
  MatBadgeModule,
  MatSortModule,
  MatAutocompleteModule,
  MatPaginatorModule
} from '@angular/material';



@NgModule({
  imports: [
    MatSlideToggleModule,
    MatTableModule,
    MatSelectModule,
    MatDialogModule,
    MatDatepickerModule,
    MatRadioModule,
    MatButtonModule,
    MatExpansionModule,
    MatStepperModule,
    MatToolbarModule,
    MatTooltipModule,
    MatNativeDateModule,
    MatSnackBarModule,
    MatProgressSpinnerModule,
    MatListModule,
    MatGridListModule,
    MatCardModule,
    MatSidenavModule,
    MatTabsModule,
    MatInputModule,
    MatTabsModule,
    MatCheckboxModule,
    MatMenuModule,
    MatIconModule,
    MatBadgeModule,
    MatSortModule,
    MatAutocompleteModule,
    MatPaginatorModule,
  ],
    exports: [
      MatSlideToggleModule,
      MatTableModule,
      MatSelectModule,
      MatDialogModule,
      MatDatepickerModule,
      MatRadioModule,
      MatButtonModule,
      MatExpansionModule,
      MatStepperModule,
      MatToolbarModule,
      MatTooltipModule,
      MatNativeDateModule,
      MatSnackBarModule,
      MatProgressSpinnerModule,
      MatListModule,
      MatGridListModule,
      MatCardModule,
      MatSidenavModule,
      MatTabsModule,
      MatInputModule,
      MatTabsModule,
      MatCheckboxModule,
      MatMenuModule,
      MatIconModule,
      MatBadgeModule,
      MatSortModule,
      MatAutocompleteModule,
      MatPaginatorModule,
    ]

})
export class MaterialModule { }
